import { Box, Button } from '@mui/material'
import { User } from '@prisma/client'
import { error } from 'console'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import Layout from '../components/Layout'
import { setBoards } from '../redux/features/boardSlice'
import { useAppDispatch, useAppSelector } from '../redux/store'
import { trpc } from '../utils/trpc'

const Home: NextPage = () => {
  const createBoard = trpc.useMutation(['board.create'])
  const dispatch = useAppDispatch()
  const router = useRouter()
  const handleCreateBoard = () => {
    createBoard.mutate(null,{
      onError:(error) => {
        alert(error.message)
      },
      onSuccess: ({board}) => {
        dispatch(setBoards([board]))
        router.push(`/boards/${board.id}`)
      }
    })
  }

  return (
    <div>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Box sx={{height: "100%", display:"flex", alignItems: "center" , justifyContent: "center"}}>
            <Button disabled={createBoard.isLoading} variant='outlined' color="success" onClick={handleCreateBoard}>
              Create your first board
            </Button>
        </Box>
      </Layout>


    </div>
  )
}

export default Home
